apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: placeholder-component
  description:
    $text: file:///proc/self/environ
spec:
  type: service
  lifecycle: production
  owner: guest
